routes/web.php
<?php

use App\Http\Controllers\Admin\Auth\ChangePasswordController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\ConfigurationController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DistrictsController;
use App\Http\Controllers\Admin\GroupsController;
use App\Http\Controllers\Admin\InquiryController;
use App\Http\Controllers\Admin\LevelsController;
use App\Http\Controllers\Admin\MagazinesController;
use App\Http\Controllers\Admin\OrganizationController;
use App\Http\Controllers\Admin\PollsController;
use App\Http\Controllers\Admin\PostsController;
use App\Http\Controllers\Admin\ProfileConntroller;
use App\Http\Controllers\Admin\StatesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\FollowsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\Organization\Auth\OrganizationLoginController;
use App\Http\Controllers\Organization\Auth\PasswordChangeController;
use App\Http\Controllers\Organization\Auth\PasswordForgotController;
use App\Http\Controllers\Organization\DashboardsController;
use App\Http\Controllers\Organization\MeetingsController;
use App\Http\Controllers\Organization\OrganizationProfileController;
use App\Http\Controllers\Organization\OrganizationUsersController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\WebController;
use App\Models\Cms;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::group(['prefix' => 'admin'], function () {
//    Route::get('/1', function ()    {
//        return 'hello';
//    });
//});






Route::get('/', [WebController::class, 'index'])->name('welcome.index');


//Get contact (contact_us )
Route::post('/contact_us/', [WebController::class, 'contact_us'])->name('contacts_inquiry.store');

Route::get('/home', [HomeController::class, 'index'])->name('home');

//Route::get('/',function (){
//    return "<h1 style='margin-left: 70vh; margin-top: 40vh'>Page under Construction</h1>";
//});
Route::get('/login', function () {
    return redirect()->route('welcome.index')->with("error_code", 'Route Not Found');
});
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login');
Auth::routes(['login' => false]);
//   admin route


Route::prefix('admin')->name('admin.')->group(function () {
    //   Admin Login
//       Auth::routes(['register' => false]);

    Route::get('/', [LoginController::class, 'adminLoginForm'])->name('showLoginForm');
    Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
    //  admin password reset
    Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

    // admin Logout
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::middleware(['is_admin'])->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');

        //  admin profile route

        Route::get('/profile', [ProfileConntroller::class, 'index'])->name('profile.index');
        Route::get('/profile/edit', [ProfileConntroller::class, 'edit'])->name('profile.edit.index');
        Route::post('/profile/update', [ProfileConntroller::class, 'update'])->name('profile.update');
        Route::post('/profile/image/update', [ProfileConntroller::class, 'upload'])->name('profile.image.update');
        //      Admin change Password
        Route::get('/change_password', [ChangePasswordController::class, 'index'])->name('change_password.index');
        Route::post('/change_password', [ChangePasswordController::class, 'changePassword'])->name('changePassword');

        // master section


        // Country
        Route::get('/country', [CountryController::class, 'index'])->name('country.index');
        Route::get('/country/create', [CountryController::class, 'create'])->name('country.create');
        Route::post('/country/store', [CountryController::class, 'store'])->name('country.store');
        Route::get('country/changeStatue', [CountryController::class, 'ChangeStatus'])->name('country.changeStatus');
        Route::get('country/remove/{id}', [CountryController::class, 'remove'])->name('country.remove');
        Route::get('country/edit/{id}', [CountryController::class, 'edit'])->name('country.edit');
        Route::post('country/update', [CountryController::class, 'update'])->name('country.update');
        // state
        Route::get('/state', [StatesController::class, 'index'])->name('state.index');
        Route::get('/state/create', [StatesController::class, 'create'])->name('state.create');
        Route::post('/state/store', [StatesController::class, 'store'])->name('state.store');
        Route::get('state/changeStatue', [StatesController::class, 'ChangeStatus'])->name('state.changeStatus');
        Route::get('state/edit/{id}', [StatesController::class, 'edit'])->name('state.edit');
        Route::post('state/update', [StatesController::class, 'update'])->name('state.update');
        Route::get('state/remove/{id}', [StatesController::class, 'remove'])->name('state.remove');
        Route::post('state/view/', [StatesController::class, 'view'])->name('state.view');

        // District
        Route::get('/district', [DistrictsController::class, 'index'])->name('district.index');
        Route::get('/district/create', [DistrictsController::class, 'create'])->name('district.create');
        Route::post('/district/store', [DistrictsController::class, 'store'])->name('district.store');
        Route::post('/district/view/', [DistrictsController::class, 'view'])->name('district.view');
        Route::get('/district/edit/{id}', [DistrictsController::class, 'edit'])->name('district.edit');
        Route::post('district/update', [DistrictsController::class, 'update'])->name('district.update');
        Route::get('district/remove/{id}', [DistrictsController::class, 'remove'])->name('district.remove');
        Route::get('district/changeStatue', [DistrictsController::class, 'ChangeStatus'])->name('district.changeStatus');
        // city
        Route::get('/city', [CityController::class, 'index'])->name('city.index');
        Route::get('/city/create', [CityController::class, 'create'])->name('city.create');
        Route::get('/city/getDistricts', [CityController::class, 'getDistrict'])->name('city.getDistricts');
        Route::post('/city/store', [CityController::class, 'store'])->name('city.store');
        Route::post('/city/view/', [CityController::class, 'view'])->name('city.view');
        Route::get('/city/edit/{id}', [CityController::class, 'edit'])->name('city.edit');
        Route::post('/city/update', [CityController::class, 'update'])->name('city.update');
        Route::get('city/remove/{id}', [CityController::class, 'remove'])->name('city.remove');
        Route::get('city/changeStatue', [CityController::class, 'ChangeStatus'])->name('city.changeStatus');

        // config section
        Route::get('/config/create', [ConfigurationController::class, 'create'])->name('config.create');
        Route::post('/config/store', [ConfigurationController::class, 'store'])->name('config.store');
        Route::get('/config', [ConfigurationController::class, 'index'])->name('config.index');
        Route::get('config/remove/{id}', [ConfigurationController::class, 'remove'])->name('config.remove');
        Route::get('config/edit/{id}', [ConfigurationController::class, 'edit'])->name('config.edit');
        Route::post('config/update', [ConfigurationController::class, 'update'])->name('config.update');
        Route::get('config/sms_api/changeStatue', [ConfigurationController::class, 'ChangeStatus'])->name('config.sms_api.changeStatus');



        // Settings  for Trending Post
        Route::get('/setting/trending/posts',[ConfigurationController::class,"trendingPost"])->name('setting.trending.post');
        Route::get('/setting/trending/posts/edit/{id}',[ConfigurationController::class,"trendingPostEdit"])->name('setting.trending.post.edit');
        Route::post('/setting/trending/posts/update/',[ConfigurationController::class,"trendingPostUpdate"])->name('setting.trending.post.update');



        // Levels
//        Route::get('/level', [LevelsController::class, 'index'])->name('level.index');
//        Route::get('/level/create/', [LevelsController::class, 'create'])->name('level.create');
//        Route::post('/level/store/', [LevelsController::class, 'store'])->name('level.store');
//        Route::get('/level/edit/{id}', [LevelsController::class, 'edit'])->name('level.edit');
//        Route::post('/level/update', [LevelsController::class, 'update'])->name('level.update');
//        Route::get('/level/remove/{id}', [LevelsController::class, 'remove'])->name('level.remove');
//        Route::get('level/changeStatue', [LevelsController::class, 'ChangeStatus'])->name('level.changeStatus');

        //Organization
        Route::get('/organization', [OrganizationController::class, 'index'])->name('organization.index');

app/Http/Controllers/Api/OrganizationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Company;

class OrganizationController extends Controller
{
    public function index(Request $request){

        $records = Company::where('status','1')->where('permission_to_make_manch_org','<>',Company::PERMISSION_TO_MAKE_MANCH_ORN)->select('id','name','name_in_hindi','sort_name','status','likeToJoin');

        $search = $request->query('search');
        if ($search) {
            $records = $records->where(function ($q) use ($search) {
                $q->where('name', 'like', '%' . $search . '%');
            });
        }
        if ($request->sort && $request->direction) {
            $records->orderBy($request->sort, $request->direction);
        } else {
            $records->orderBy("name");

        }
        $limit = $request->record_per_page;


        $limit = 10000;

        $records = $records->paginate((int)$limit);


        if(count($records)>0){
            return response()->json([
               'status_code'=>1,
               'message'=>'Organizations Found SuccessFully',
                'data'=> $records
            ]);
        }else{
            return response()->json([
                'status_code'=>0,
                'message'=>'Organizations Not found!',
                'data'=>null

            ]);
        }
    }
}

app/Http/Controllers/Organization/DashboardsController.php
<?php

namespace App\Http\Controllers\Organization;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Inquiry;
use App\Models\Meeting;
use App\Models\Pole;
use App\Models\Post;
use App\Models\User;
use App\Models\UserCompany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardsController extends Controller
{
    public function __construct()
    {

    }

//  organization dashboard index
    public function index(Request $request)
    {
        $user = Auth::user()->userComapny()->first();
        $orgUsers = UserCompany::where('company_id', $user->company_id)->pluck('user_id')->toArray();
        $userId = array_values(array_unique($orgUsers));

        $Posts = Post::WhereIn('user_id', $userId)->withCount('likes')->count();
        $users = $orgUsers;


        $polls = Pole::whereIn('user_id', $orgUsers)->where('status', 1)->count();

//        meeting received
        $logInUser = UserCompany::whereIn('user_id', array(Auth::user()->id))->pluck('company_id')->toArray();
        $records = Meeting::whereIn('company_id', $logInUser)->whereNotIn('user_id', [Auth::user()->id])->with('Organization');
        //dd($records);
        if ($request->query('search')) {
            $records = $records->where(function ($q) use ($request) {
                $q->where('description', 'like', '%' . $request->query('search') . '%');
                $q->orwhere('created_at', 'like', '%' . $request->query('search') . '%');

            });
        }
        if ($request->sort && $request->direction) {

            $records->orderBy($request->sort, $request->direction);
        } else {
            $records->orderBy("id", "DESC");

        }
        $records = $records->paginate(($request->query('limit') ? $request->query('limit') : env('PAGINATION_LIMIT')));

        return view('organization.dashboard.dashboard', compact('users', 'Posts', 'polls', 'records'));
    }
}

app/Http/Controllers/Organization/OrganizationProfileController.php
<?php

namespace App\Http\Controllers\Organization;

use App\Http\Controllers\Controller;

use App\Http\Requests\organization\OrganizationUpdateProfileRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Exception;
use Illuminate\Validation\Rule;

class OrganizationProfileController extends Controller
{
    public function __construct(){

    }

//    organization Profile View
    public function index(){
        $user = User::find(Auth::user()->id);

        return view('organization.profile.index',compact('user'));
    }
    public function edit(){
        $user = User::find(Auth::user()->id);
        return view('organization.profile.edit',compact('user'));
    }

    public function upload(Request $request)
    {
        try{
        $user = User::find(Auth::user()->id);
        $oldImage= $user->profile_pic;
        if($oldImage && file_exists(public_path(User::PROFILE_PIC_PATH.$oldImage))){
            @unlink(public_path(User::PROFILE_PIC_PATH.$oldImage));
        }
        $folderPath = public_path('admin/profile/');

        $image_parts = explode(";base64,", $request->image);
        $image_type_aux = explode("image/", $image_parts[0]);
        $image_type = $image_type_aux[1];
        $image_base64 = base64_decode($image_parts[1]);
        $file =  uniqid() . '.jpg';
        $file_ = $folderPath . $file;

        file_put_contents($file_, $image_base64);
       User::find(Auth::user()->id)->update(['profile_pic' =>$file ]);
        return response()->json(['type'=>'success','message'=>"Profile Image Updated Successfully",'url'=> asset(User::PROFILE_PIC_PATH.$file)]);
        } catch (Exception $e) {
            Log::info('Log message', ['error' => $e->getMessage()]);
        }
    }

    public function update(OrganizationUpdateProfileRequest $request){
        try{

         //   $role = Role::where('slug','super_admin')->first();
            $editProfile = User::find(Auth::user()->id);
            $requestData = $request->validated();
            $editProfile->fill($requestData);
           // $editProfile->role_id=$role->id;
            $editProfile->save();
            $request->session()->flash('title'," Hello ".Auth::user()->first_name." ".Auth::user()->last_name);
            $request->session()->flash('success',"Profile Update Successfully.");
               return back();


        } catch (Exception $e) {
            Log::info('Log message', ['error' => $e->getMessage()]);
            }

    }
}

resources/views/organization/organizations/edit.blade.php
@extends('layouts.organization.app')
@section('title','Update Organizations')

@section('content')

    <!-- Sidebar Area End Here -->
    <div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">
            <ul>
                <li>
                    <a href="{{route('admin.dashboard.index')}}">Home</a>
                </li>
                <li>Add New Organization</li>
            </ul>
        </div>
        <div class="card height-auto">
            <div class="card-body">

                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>Add New Organization</h3>
                    </div>
                </div>
                <form class="new-added-form" action="{{route('admin.organization.update')}}" method="post">
                    @csrf
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-12 form-group">
                            <label>Organization Name *</label>
                            <label>

                                <input type="text" name="company_id" class="hidden" value="{{$record->id}}"/>
                                <input type="text" name="user_id" class="hidden" value="{{@$user->id}}"/>
                                <input type="text" placeholder="" class="@error('org_name') is-invalid @enderror form-control" name="org_name" value="{{$record->name}}"/>

                            </label>
                            @error('org_name')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        {{--                        <input type="hidden" name="company_id" value="{{$record->company->id}}">--}}
                        {{--                        <input type="hidden" name="user_id" value="{{$record->id}}">--}}
                        <div class="col-xl-6 col-lg-6 col-12 form-group">
                            <label>Organization email </label>
                            <label>
                                <input type="email" placeholder=""
                                       class="@error('email') is-invalid @enderror form-control" name="email"
                                       value="{{$record->email}}"/>
                            </label>
                            @error('email')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>State* </label>
                            <label>

                                <select class=" select_state_dist select2  @error('state_id') is-invalid @enderror " name="state_id" onchange="onselectState()">

                                    <option value="">Please Select</option>
                                    @foreach ($states as $state)
                                        <option value="{{$state->id}}"
                                                @if(($record->state_id)==$state->id) Selected @endif>{{$state->name}}</option>
                                    @endforeach
                                </select>
                            </label>
                            @error('state_id')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>District *</label>
                            <label>
                                <select value=""
                                        class="select2 seclected_dist  @error('district_id') is-invalid @enderror "
                                        name="district_id" id="state" onchange="onselectDistrict()">
                                    <option value="">Please Select</option>
                                </select>
                            </label>
                            @error('district_id')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>City *</label>
                            <label>

                                <select class="select2 citySelector   @error('city_id') is-invalid @enderror " name="city_id" id="cities">

                                    <option value="">Please Select</option>
                                </select>
                            </label>
                            @error('city_id')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>Status*</label>
                            <label>
                                <select class="select2  @error('status') is-invalid @enderror " name="status">
                                    <option value="">Please Select</option>

                                    <option value="1" @if(($record->status)==1) Selected @endif>Active</option>
                                    <option value="0" @if(($record->status)==0) Selected @endif>Inactive</option>

                                </select>
                            </label>
                            @error('status')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-9 col-lg-6 col-12 form-group">
                            <label>Address </label>
                            <label>
                                <input type="text" placeholder=""
                                       class="@error('address') is-invalid @enderror form-control" name="address"
                                       value="{{$record->address}}"/>
                            </label>
                            @error('address')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>Postal Code </label>
                            <label>
                                <input type="text" placeholder=""
                                       class="@error('postal_code') is-invalid @enderror form-control"
                                       name="postal_code" value="{{$record->postal_code}}"/>
                            </label>
                            @error('postal_code')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
{{--                        <div class="col-xl-3 col-lg-6 col-12 form-group">--}}
{{--                            <label>User First Name *</label>--}}
{{--                            <label>--}}
{{--                                <input type="text" placeholder=""--}}
{{--                                       class="@error('first_name') is-invalid @enderror form-control" name="first_name"--}}
{{--                                       value="{{@$user->first_name}}"/>--}}
{{--                            </label>--}}
{{--                            @error('first_name')--}}
{{--                            <span role="alert">--}}
{{--                            <strong class="text-danger">{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                            @enderror--}}
{{--                        </div>--}}
{{--                        <div class="col-xl-3 col-lg-6 col-12 form-group">--}}
{{--                            <label>User Last Name *</label>--}}
{{--                            <label>--}}
{{--                                <input type="text" placeholder=""--}}
{{--                                       class="@error('last_name') is-invalid @enderror form-control" name="last_name"--}}
{{--                                       value="{{@$user->last_name}}"/>--}}
{{--                            </label>--}}
{{--                            @error('last_name')--}}
{{--                            <span role="alert">--}}
{{--                            <strong class="text-danger">{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                            @enderror--}}
{{--                        </div>--}}
{{--                        <div class="col-xl-3 col-lg-6 col-12 form-group">--}}
{{--                            <label>User Email* </label>--}}
{{--                            <label>--}}
{{--                                <input type="text" placeholder=""--}}
{{--                                       class="@error('user_email') is-invalid @enderror form-control" name="user_email"--}}
{{--                                       value="{{@$user->email}}"/>--}}
{{--                            </label>--}}
{{--                            @error('user_email')--}}
{{--                            <span role="alert">--}}
{{--                            <strong class="text-danger">{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                            @enderror--}}
{{--                        </div>--}}
{{--                        <div class="col-xl-3 col-lg-6 col-12 form-group">--}}
{{--                            <label>User Phone No* </label>--}}
{{--                            <label>--}}
{{--                                <input type="text" placeholder=""--}}
{{--                                       class="@error('mobile') is-invalid @enderror form-control" name="mobile"--}}
{{--                                       value="{{@$user->mobile}}"/>--}}
{{--                            </label>--}}
{{--                            @error('mobile')--}}
{{--                            <span role="alert">--}}
{{--                            <strong class="text-danger">{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                            @enderror--}}
{{--                        </div>--}}
                        <div class="col-xl-3 col-lg-6 col-12 form-group">
                            <label>User Designation *</label>

                            <select class="select2 selected_designation @error('designation') is-invalid @enderror" onchange="onselectDesignation()" name="designation">

                                <option value="">Please Select Section *</option>
                                @foreach($levels as $destination )
                                    <option value="{{$destination->id}}" >{{$destination->name}}</option>
                                @endforeach
                            </select>
                            @error('designation')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-xl-6 col-lg-6 col-12 form-group ">
                            <label>Organizations Designation *</label>

                            <select class="select2 border-0 designation @error('companydesignations') is-invalid @enderror" multiple id="designation" name="companydesignations[]">

                                <option value="">Please Select Section *</option>
                            </select>
                            @error('companydesignations')
                            <span role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>


                        <div class="col-12 form-group mg-t-8">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save
                            </button>
                            <a href="{{route('admin.city.index')}}" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    @include('organization.organizations.updateScript')



@endsection