routes/web.php
<?php

use App\Http\Controllers\Admin\Auth\ChangePasswordController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\ConfigurationController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DistrictsController;
use App\Http\Controllers\Admin\GroupsController;
use App\Http\Controllers\Admin\InquiryController;
use App\Http\Controllers\Admin\LevelsController;
use App\Http\Controllers\Admin\MagazinesController;
use App\Http\Controllers\Admin\OrganizationController;
use App\Http\Controllers\Admin\PollsController;
use App\Http\Controllers\Admin\PostsController;
use App\Http\Controllers\Admin\ProfileConntroller;
use App\Http\Controllers\Admin\StatesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\FollowsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\Organization\Auth\OrganizationLoginController;
use App\Http\Controllers\Organization\Auth\PasswordChangeController;
use App\Http\Controllers\Organization\Auth\PasswordForgotController;
use App\Http\Controllers\Organization\DashboardsController;
use App\Http\Controllers\Organization\MeetingsController;
use App\Http\Controllers\Organization\OrganizationProfileController;
use App\Http\Controllers\Organization\OrganizationUsersController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\WebController;
use App\Models\Cms;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::group(['prefix' => 'admin'], function () {
//    Route::get('/1', function ()    {
//        return 'hello';
//    });
//});






Route::get('/', [WebController::class, 'index'])->name('welcome.index');


//Get contact (contact_us )
Route::post('/contact_us/', [WebController::class, 'contact_us'])->name('contacts_inquiry.store');

Route::get('/home', [HomeController::class, 'index'])->name('home');

//Route::get('/',function (){
//    return "<h1 style='margin-left: 70vh; margin-top: 40vh'>Page under Construction</h1>";
//});
Route::get('/login', function () {
    return redirect()->route('welcome.index')->with("error_code", 'Route Not Found');
});
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login');
Auth::routes(['login' => false]);
//   admin route


Route::prefix('admin')->name('admin.')->group(function () {
    //   Admin Login
//       Auth::routes(['register' => false]);

    Route::get('/', [LoginController::class, 'adminLoginForm'])->name('showLoginForm');
    Route::post('/login', [LoginController::class, 'postLogin'])->name('login');
    //  admin password reset
    Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

    // admin Logout
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

    Route::middleware(['is_admin'])->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');

        //  admin profile route

        Route::get('/profile', [ProfileConntroller::class, 'index'])->name('profile.index');
        Route::get('/profile/edit', [ProfileConntroller::class, 'edit'])->name('profile.edit.index');
        Route::post('/profile/update', [ProfileConntroller::class, 'update'])->name('profile.update');
        Route::post('/profile/image/update', [ProfileConntroller::class, 'upload'])->name('profile.image.update');
        //      Admin change Password
        Route::get('/change_password', [ChangePasswordController::class, 'index'])->name('change_password.index');
        Route::post('/change_password', [ChangePasswordController::class, 'changePassword'])->name('changePassword');

        // master section


        // Country
        Route::get('/country', [CountryController::class, 'index'])->name('country.index');
        Route::get('/country/create', [CountryController::class, 'create'])->name('country.create');
        Route::post('/country/store', [CountryController::class, 'store'])->name('country.store');
        Route::get('country/changeStatue', [CountryController::class, 'ChangeStatus'])->name('country.changeStatus');
        Route::get('country/remove/{id}', [CountryController::class, 'remove'])->name('country.remove');
        Route::get('country/edit/{id}', [CountryController::class, 'edit'])->name('country.edit');
        Route::post('country/update', [CountryController::class, 'update'])->name('country.update');
        // state
        Route::get('/state', [StatesController::class, 'index'])->name('state.index');
        Route::get('/state/create', [StatesController::class, 'create'])->name('state.create');
        Route::post('/state/store', [StatesController::class, 'store'])->name('state.store');
        Route::get('state/changeStatue', [StatesController::class, 'ChangeStatus'])->name('state.changeStatus');
        Route::get('state/edit/{id}', [StatesController::class, 'edit'])->name('state.edit');
        Route::post('state/update', [StatesController::class, 'update'])->name('state.update');
        Route::get('state/remove/{id}', [StatesController::class, 'remove'])->name('state.remove');
        Route::post('state/view/', [StatesController::class, 'view'])->name('state.view');

        // District
        Route::get('/district', [DistrictsController::class, 'index'])->name('district.index');
        Route::get('/district/create', [DistrictsController::class, 'create'])->name('district.create');
        Route::post('/district/store', [DistrictsController::class, 'store'])->name('district.store');
        Route::post('/district/view/', [DistrictsController::class, 'view'])->name('district.view');
        Route::get('/district/edit/{id}', [DistrictsController::class, 'edit'])->name('district.edit');
        Route::post('district/update', [DistrictsController::class, 'update'])->name('district.update');
        Route::get('district/remove/{id}', [DistrictsController::class, 'remove'])->name('district.remove');
        Route::get('district/changeStatue', [DistrictsController::class, 'ChangeStatus'])->name('district.changeStatus');
        // city
        Route::get('/city', [CityController::class, 'index'])->name('city.index');
        Route::get('/city/create', [CityController::class, 'create'])->name('city.create');
        Route::get('/city/getDistricts', [CityController::class, 'getDistrict'])->name('city.getDistricts');
        Route::post('/city/store', [CityController::class, 'store'])->name('city.store');
        Route::post('/city/view/', [CityController::class, 'view'])->name('city.view');
        Route::get('/city/edit/{id}', [CityController::class, 'edit'])->name('city.edit');
        Route::post('/city/update', [CityController::class, 'update'])->name('city.update');
        Route::get('city/remove/{id}', [CityController::class, 'remove'])->name('city.remove');
        Route::get('city/changeStatue', [CityController::class, 'ChangeStatus'])->name('city.changeStatus');

        // config section
        Route::get('/config/create', [ConfigurationController::class, 'create'])->name('config.create');
        Route::post('/config/store', [ConfigurationController::class, 'store'])->name('config.store');
        Route::get('/config', [ConfigurationController::class, 'index'])->name('config.index');
        Route::get('config/remove/{id}', [ConfigurationController::class, 'remove'])->name('config.remove');
        Route::get('config/edit/{id}', [ConfigurationController::class, 'edit'])->name('config.edit');
        Route::post('config/update', [ConfigurationController::class, 'update'])->name('config.update');
        Route::get('config/sms_api/changeStatue', [ConfigurationController::class, 'ChangeStatus'])->name('config.sms_api.changeStatus');



        // Settings  for Trending Post
        Route::get('/setting/trending/posts',[ConfigurationController::class,"trendingPost"])->name('setting.trending.post');
        Route::get('/setting/trending/posts/edit/{id}',[ConfigurationController::class,"trendingPostEdit"])->name('setting.trending.post.edit');
        Route::post('/setting/trending/posts/update/',[ConfigurationController::class,"trendingPostUpdate"])->name('setting.trending.post.update');



        // Levels
//        Route::get('/level', [LevelsController::class, 'index'])->name('level.index');
//        Route::get('/level/create/', [LevelsController::class, 'create'])->name('level.create');
//        Route::post('/level/store/', [LevelsController::class, 'store'])->name('level.store');
//        Route::get('/level/edit/{id}', [LevelsController::class, 'edit'])->name('level.edit');
//        Route::post('/level/update', [LevelsController::class, 'update'])->name('level.update');
//        Route::get('/level/remove/{id}', [LevelsController::class, 'remove'])->name('level.remove');
//        Route::get('level/changeStatue', [LevelsController::class, 'ChangeStatus'])->name('level.changeStatus');

        //Organization
        Route::get('/organization', [OrganizationController::class, 'index'])->name('organization.index');

app/Models/Post.php
<?php

namespace App\Models;

use App\Helpers\CommonHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;


class Post extends Model
{
    protected $appends = ['is_like', 'is_Post', 'is_report', 'company_approved', "post_created_at"];

    const  Active = 1;
    const  Inactive = 0;

    use HasFactory;

    protected $fillable = ['company_id', 'user_id', 'description', 'slug', 'like_count', 'comment_count', 'type', 'status'];


    public function getIsLikeAttribute()
    {
        $isLike = PostLike::where(['post_id' => $this->id, 'user_id' => Auth::user()->id])->get();
        if (count($isLike) > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function getIsReportAttribute()
    {
        $isReport = Report::where(['post_id' => $this->id, 'user_id' => Auth::user()->id])->count();
        if ($isReport > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function getPostCreatedAtAttribute()
    {
        if (!empty($this->attributes['created_at'])) {
            return @$this->created_at->diffForHumans();
        } else {
            return "";
        }
    }

    public function getCompanyApprovedAttribute()
    {
        $WantTOJoin = CommonHelper::WantTOJoin();

        foreach ($WantTOJoin as $userId) {
            if ($userId == $this->user_id) {
                return 1;
            } else {
                return 0;
            }
        }
    }

    public function getIsPostAttribute()
    {
        return true;
    }

    public function getPostImage()
    {
        return $this->hasMany('App\Models\PostImage')->select('id', 'post_id', 'image');

    }

    public function report()
    {
        return $this->hasMany('App\Models\Report')->select('id', 'post_id', 'user_id');

    }

    public function getPostVideo()
    {
        return $this->hasMany('App\Models\PostVideo')->select('id', 'post_id', 'video','thumbnail');

    }

    public function getUser()
    {
        return $this->belongsTo(User::class, 'user_id', 'id')->select('id', 'first_name', 'last_name', 'profile_pic',);
    }

    public function postBy()
    {
        return $this->belongsTo(User::class, 'user_id', 'id')->select('id', 'first_name', 'last_name', 'profile_pic');
    }

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id', 'id')->select('id', 'first_name', 'last_name', 'profile_pic');
    }

    public function getCompany()
    {
        return $this->belongsTo(Company::class, 'company_id', 'id')->select('id', 'name');
    }

    public function comments()
    {
        return $this->hasMany(PostComment::class);
    }

    public function likes()
    {
        return $this->hasMany(PostLike::class)->select('id', 'user_id', 'post_id');
    }

    public function replies()
    {
        return $this->hasMany(PostComment::class, 'parent_id',);
    }

    public function reports()
    {
        return $this->hasMany(Report::class, 'post_id', 'id');
    }


}

app/Http/Controllers/Api/OrganizationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Company;

class OrganizationController extends Controller
{
    public function index(Request $request){

        $records = Company::where('status','1')->where('permission_to_make_manch_org','<>',Company::PERMISSION_TO_MAKE_MANCH_ORN)->select('id','name','name_in_hindi','sort_name','status','likeToJoin');

        $search = $request->query('search');
        if ($search) {
            $records = $records->where(function ($q) use ($search) {
                $q->where('name', 'like', '%' . $search . '%');
            });
        }
        if ($request->sort && $request->direction) {
            $records->orderBy($request->sort, $request->direction);
        } else {
            $records->orderBy("name");

        }
        $limit = $request->record_per_page;


        $limit = 10000;

        $records = $records->paginate((int)$limit);


        if(count($records)>0){
            return response()->json([
               'status_code'=>1,
               'message'=>'Organizations Found SuccessFully',
                'data'=> $records
            ]);
        }else{
            return response()->json([
                'status_code'=>0,
                'message'=>'Organizations Not found!',
                'data'=>null

            ]);
        }
    }
}

app/Http/Controllers/Organization/DashboardsController.php
<?php

namespace App\Http\Controllers\Organization;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Inquiry;
use App\Models\Meeting;
use App\Models\Pole;
use App\Models\Post;
use App\Models\User;
use App\Models\UserCompany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardsController extends Controller
{
    public function __construct()
    {

    }

//  organization dashboard index
    public function index(Request $request)
    {
        $user = Auth::user()->userComapny()->first();
        $orgUsers = UserCompany::where('company_id', $user->company_id)->pluck('user_id')->toArray();
        $userId = array_values(array_unique($orgUsers));

        $Posts = Post::WhereIn('user_id', $userId)->withCount('likes')->count();
        $users = $orgUsers;


        $polls = Pole::whereIn('user_id', $orgUsers)->where('status', 1)->count();

//        meeting received
        $logInUser = UserCompany::whereIn('user_id', array(Auth::user()->id))->pluck('company_id')->toArray();
        $records = Meeting::whereIn('company_id', $logInUser)->whereNotIn('user_id', [Auth::user()->id])->with('Organization');
        //dd($records);
        if ($request->query('search')) {
            $records = $records->where(function ($q) use ($request) {
                $q->where('description', 'like', '%' . $request->query('search') . '%');
                $q->orwhere('created_at', 'like', '%' . $request->query('search') . '%');

            });
        }
        if ($request->sort && $request->direction) {

            $records->orderBy($request->sort, $request->direction);
        } else {
            $records->orderBy("id", "DESC");

        }
        $records = $records->paginate(($request->query('limit') ? $request->query('limit') : env('PAGINATION_LIMIT')));

        return view('organization.dashboard.dashboard', compact('users', 'Posts', 'polls', 'records'));
    }
}

resources/views/organization/posts/create.blade.php
@extends('layouts.organization.app')

@section('title','Create Company Post')

@section('content')
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <!-- Sidebar Area End Here -->
    <div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">
            <ul>
                <li>
                    <a href="{{route('organization.dashboards.index')}}">Home</a>
                </li>
                <li>Add New Company Post</li>
            </ul>
        </div>
        <!-- Breadcubs Area End Here -->
        <!-- Admit Form Area Start Here -->
        <div class="card height-auto">
            <div class="card-body">
                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>Add New Company Post</h3>
                    </div>

                </div>
                <form class="new-added-form" action="{{route('organization.posts.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">

                       <div>
                        <div class="col-lg-6 col-2 form-group mg-t-30">
                            <label class="text-dark-medium" style="margin-top:-17px">Image</label>
                            <input type="file" class="form-control-file @error('images') is-invalid @enderror" name="images[]" multiple>

                        </div>
                           @error('images')
                           <span  role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                           @enderror
                       </div>

                        <div>
                        <div class="col-lg-6 col-2 form-group mg-t-30">
                            <label class="text-dark-medium" style="margin-top:-17px">Video</label>
                            <input type="file" class="form-control-file @error('videos') is-invalid @enderror" name="videos[]" multiple>

                        </div>
                           @error('videos')
                           <span  role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                           @enderror
                       </div>

                        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Content</label>
                                <textarea name="editor1"></textarea>
                                <script>
                                    CKEDITOR.replace( 'editor1' );
                                </script>

                                @if ($errors->has('editor1'))
                                    <span class="error-message">
                                            <strong  class="text-danger">{{ $errors->first('editor1') }}</strong>
                                        </span>
                                @endif


                            </div>
                        </div>
                        <div class="col-12 form-group mg-t-8">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
@endsection

resources/views/organization/posts/create_personal_post.blade.php
@extends('layouts.organization.app')

@section('title','Create  Post')

@section('content')
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <!-- Sidebar Area End Here -->
    <div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">
            <ul>
                <li>
                    <a href="{{route('organization.dashboards.index')}}">Home</a>
                </li>
                <li>Add New Post</li>
            </ul>
        </div>
        <!-- Breadcubs Area End Here -->
        <!-- Admit Form Area Start Here -->
        <div class="card height-auto">
            <div class="card-body">
                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>Add New Post</h3>
                    </div>

                </div>
                <form class="new-added-form" action="{{route('organization.posts.store.personal')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">

                       <div>
                        <div class="col-lg-6 col-2 form-group mg-t-30">
                            <label class="text-dark-medium" style="margin-top:-17px">Image</label>
                            <input type="file" class="form-control-file @error('images') is-invalid @enderror" name="images[]" multiple>

                        </div>
                           @error('images')
                           <span  role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                           @enderror
                       </div>

                        <div>
                        <div class="col-lg-6 col-2 form-group mg-t-30">
                            <label class="text-dark-medium" style="margin-top:-17px">Video</label>
                            <input type="file" class="form-control-file @error('videos') is-invalid @enderror" name="videos[]" multiple>

                        </div>
                           @error('videos')
                           <span  role="alert">
                            <strong class="text-danger">{{ $message }}</strong>
                            </span>
                           @enderror
                       </div>

                        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Content</label>
                                <textarea name="editor1"></textarea>
                                <script>
                                    CKEDITOR.replace( 'editor1' );
                                </script>

                                @if ($errors->has('editor1'))
                                    <span class="error-message">
                                            <strong  class="text-danger">{{ $errors->first('editor1') }}</strong>
                                        </span>
                                @endif


                            </div>
                        </div>
                        <div class="col-12 form-group mg-t-8">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
@endsection

resources/views/organization/posts/display.blade.php
@extends('layouts.organization.app')

@section('title','Posts')


@section('content')
<div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">

        </div>
        <!-- Breadcubs Area End Here -->
        <!-- Admit Form Area Start Here -->
        <div class="card height-auto">
            <div class="card-body">
                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>Post Details</h3>
                    </div>

                </div>
                <form class="new-added-form" action="" method="get" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                             <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                            <div class="form-group">
                                <label class="control-label" style="font-weight: bold;">Content:</label>
                                {!! $post->description !!}

                            </div>
                        </div>

                        @foreach($postImage as $value)

                            @if($value->post_image != " " )
                        <div class="col-sm-3  mg-t-30" style="padding:15px;">
                                    <div class="card border" style="width: 21rem; padding-bottom: 0px;" >
                                        <img class="card-img-top" src="{{$value->post_image}}" data-id="{{$value->id}}" alt="Card image cap" style="height:25rem" >
                                    </div>
                                </div>
                            @endif
                            @endforeach
                        @foreach($postVideo as $value)
                            @if($value->post_video != " " )
                        <div class="col-sm-3  mg-t-30" style="padding:15px;">
                                    <div class="card border" style="width: 21rem; padding-bottom: 0px;" >
                                        <video width="350" height="" controls class="thumb" data-full="{{$value->id}}"style="height:100%" >
                                              <source src="{{$value->post_video}}">
                                        </video>
                                    </div>
                                </div>
                            @endif
                            @endforeach

                        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                            <div class="form-group">
                                <label class="control-label" style="font-weight: bold;">Posted  BY:</label>
                                {{$post->getUser->full_name}}

                            </div>
                        </div>


                    </div>
                </form>
            </div>
        </div>


@endsection

resources/views/organization/posts/script.blade.php
<script>
    const removeImage = (id) =>{
        $.ajax({
            type: "GET",
            url: "{{url('/organization/posts/remove/image/')}}/" + id,
            success: function (response) {
                toastr[response.type](response.message)
                document.getElementById(id).style.display = "none";
            },
            error: function(response) {
            }
        });
    }
    const removeVideo =(id) =>{
        $.ajax({
            type: "GET",
            url: "{{url('/organization/posts/remove/video/')}}/" + id,
            success: function (response) {
                toastr[response.type](response.message)
                document.getElementById(id).style.display = "none";
                location.reload();
            },
            error: function(response) {

            }
        });
    }
</script>

resources/views/organization/posts/selectPostType.blade.php
@extends('layouts.organization.app')

@section('title','Select Posts type')

@section('content')

    <style>
        .search{
            height: 50px;
        }
    </style>
    <!-- Sidebar Area End Here -->
    <div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">
            <ul>
                <li>
                    <a href="{{route('organization.dashboards.index')}}">Home</a>
                </li>
                <li>Select Posts type</li>
            </ul>
        </div>
        <!-- Breadcubs Area End Here -->
        <!-- Student Table Area Start Here -->
        <div class="card height-auto">
            <div class="card-body">
                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>Select Posts type</h3>
                    </div>

                </div>
                <div class="container col-lg-3 mt-5 col-sm-12">
                    <a href="{{route('organization.posts.create.personal')}}" class="fw-btn-fill bg-blue-dark btn-hover-yellow    text-center" >Personal Post</a>

                </div>
                <div class="container col-lg-3 mt-5 col-sm-12">
                <a href="{{route('organization.posts.create.company')}}" class="fw-btn-fill bg-blue-dark btn-hover-yellow    text-center" >Company Post</a>
                </div>
            </div>
        </div>

@endsection

resources/views/organization/posts/view.blade.php
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
<div class="my-profile proposal-details">
    <h3 class="main-job-heading">Post Details</h3>
    <div class="row">
        <div class="col-md-12">
            <div class="user">
                <img src="" class="img-fluid"/>
            </div>
            <div class="user-details-inner detail-modal">
                <h2> <!--p><i class="icofont-location-pin"></i> <span>Noida, India</span></p--></h2>
                <ul class="details-user row">
                    <li class="col-lg-12">
                        <h1>{!!  \Illuminate\Support\Str::limit($record->description ,75, $end='...')!!}</h1>
                    </li>
                    <li class="col-lg-6">
                        <p>Posted  BY: {{$record->getUser->full_name}}</p>
                    </li>
                        <div class="col-lg-12 col-12 form-group mg-t-30">
                        <div class="row">
                            @foreach($postImage as $value)
                                <div class="col-sm-3  mg-t-30" style="padding:15px;">
                                    <div class="card border" style="width: 21rem; " >
                                        <img class="card-img-top" src="{{$value->post_image}}" data-id="{{$value->id}}" alt="Card image cap" style="height:25rem" >
                                    </div>
                                </div>
                            @endforeach
                        </div>
                        </div>


                    <li class="col-lg-12">
                        <p>Description:
                           {!! $record->description !!}

                        </p>
                    </li>
                </ul>
            </div>

            <br/>

        </div>
    </div>
</div>